### ISSUE TITLE
Change a couple plist file extensions to support Sublime Text 2?

### ISSUE THREAD

**Issue by jarhart** [textmate/scheme.tmbundle#2]
Sublime Text 2 supports textmate bundles but doesn't pick up .plist files.

Would it be possible to rename Scheme.plist to Scheme.tmLanguage and Miscellaneous.plist to Miscellaneous.tmPreferences so we Sublime users can more easily use this awesome bundle?

**Comment by infininight** [comment]
Currently there are some grammar changes we've made with the bundles that aren't supported in Sublime Text, so you'll need to use the 1.x branch for Sublime. Since that's not a branch that will ever change it's probably not worth fooling with. Should Sublime once again reach parity we can look at changing the extensions.
